spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/cargo-amigo-db
#    username: postgres
#    password:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Automatically update schema (optional)
    hibernate:
      ddl-auto: update
    # Show SQL queries in logs (optional)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    jwt:
      SECRET_KEY: ChangeMeOnProductionPleaseBecauseIAMNotSecure*100Percent!!!
      ACCESS_TOKEN_VALIDITY_SECONDS: 300000
      REFRESH_TOKEN_VALIDITY_SECONDS: 900000
