name: Continuous Integration

on:
  push:
    branches:
      - develop
      - main
      - master

jobs:
  build:

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: cargoamigo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    

    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "Start building project!"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cargoamigo
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres

      - name: Show files
        run: ls -la

      - name: Build docker image
        run: docker build -t cargoamigo:latest

      - name: Verify docker image
        run: docker images